---

# write package config

- include: ../../../vundb-portage/tasks/gentoo/main.yml
  vars:
    portage_configuration:
      - section: "package.accept_keywords"
        file: "dev-util-jenkins-bin"
        entries:
          - "=dev-util/jenkins-bin-2.57 ~amd64"
    portage_packages: []


# install jenkins

- name: install jenkins
  become: yes
  portage: package="dev-util/jenkins-bin" state="present" newuse=yes update=yes


# configure jenkins

- name: ensure setup wizard is disabled
  become: yes
  lineinfile:
    dest: "/etc/conf.d/jenkins"
    regexp: '^JENKINS_JAVA_OPTIONS="(.*)(?<! -Djenkins.install.runSetupWizard=false)"$'
    line: 'JENKINS_JAVA_OPTIONS="\1 -Djenkins.install.runSetupWizard=false"'
    backrefs: yes
  notify: jenkins - restart
