---

# fail when distribution is not supported

- name: check if distribution is supported
  fail: msg="'{{ ansible_distribution }}' is not supported by this role"
  when: ansible_distribution not in ["Gentoo"]


# run os specific tasks

- include: gentoo/main.yml
  when: ansible_distribution == "Gentoo"


# execute post tasks

- name: ensure jenkins is running
  become: yes
  service: name="jenkins" state="started" enabled=yes
